In [ ]:
import numpy as np
v = np.array([1,0])
A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])

In [ ]:
# Matrix Addition
np.add(A, B)
A+B

In [ ]:
# Matrix Subtraction
np.subtract(A, B)
B-A

In [ ]:
# Matrix times vector
np.matmul(A, v)
A.dot(v)
A @ v

In [ ]:
# Matrix times matrix
np.matmul(A, B)
A.dot(B)
A @ B

In [ ]:
np.linalg.det(A)

# Check if matrix is singular
def is_singular(m):
    if (np.linalg.det(m)):
        print("Non singular matrix")
    else:
        print("Singular matrix")

is_singular(A)

In [ ]:
# Matrix Inverse
np.linalg.inv(A)
np.linalg.inv(B)

In [41]:
# System of equations Ax = b
A = np.array([[1,2,3], [2,5,2], [6,-3,1]])
b = np.array([6,4,2])

x = np.linalg.inv(A) @ b
print(x)

[1.11022302e-16 4.16333634e-17 2.00000000e+00]


In [ ]:
# Rounding
print(np.pi)
print(x)
print(A/7)

round(np.pi)
round(np.pi, 3)

print("x = ", np.around(x, 3))
print("A/7 = \n", np.around(A/7, 3))

#if you only need for displaying, you can use
np.set_printoptions(precision=3)

In [ ]:
# creae identity matrices
I2 = np.eye(2)
I3 = np.identity(3)

# size and shape
print(I3.size)
print(I3.shape)

In [ ]:
print(A)

# access the element at row i column j
A[2,1]
A[2][1]

# access the entire row or column
A[1]
A[:,2]

[[ 1  2  3]
 [ 2  5  2]
 [ 6 -3  1]]


array([ 2,  5, -3])

In [ ]:
# Elimintation matrix
E21 = np.eye(3)
E21[1,0] = -2

E31 = np.eye(3)
E31[2,0] = -6
A2 = E31 @ A

E32 = np.eye(3)
E32[2,1] = 15
A3 = E32 @ A2

In [44]:
E = E32 @ (E31 @ E21)
print(E @ A)
print(E @ b)

np.linalg.inv(E @ A) @ (E @ b)

[[  1.   2.   3.]
 [  0.   1.  -4.]
 [  0.   0. -77.]]
[   6.   -8. -154.]


array([-3.55271368e-15,  0.00000000e+00,  2.00000000e+00])

In [46]:
# Permuation matrix
I = np.eye(3)
P = I.copy() # don't use P = I

# exchange row 2 and row 3
P[1] = I[2]
P[2] = I[1]
print(P)

print(A)
print(P @ A)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[ 1  2  3]
 [ 2  5  2]
 [ 6 -3  1]]
[[ 1.  2.  3.]
 [ 6. -3.  1.]
 [ 2.  5.  2.]]


In [65]:
"""
Generate a 3 × 3 matrix with random integer element values
from 1..9, (assuming it is non-singular), then find the
Elimination matrix for this random matrix and the result
after elimination.
For example, if the function is called mat_elim(A)
"""
def mat_randint(s):
    return np.random.randint(low=1, high=9, size=(s,s))

def mat_elim(A):
    n = A.shape[0]
    E = np.eye(n)
    for i in range(n-1):
        for j in range(i+1, n):
            E[j,i] = -A[j,i]/A[i,i]
    return E

# A = np.array([[1,1,8], [5,1,3], [7,6,6]])
A = mat_randint(3)
print("\nA = \n", A)
E = mat_elim(A)
print("E = \n", E)
print("\nEA = \n", np.around(E @ A, 3))



A = 
 [[6 5 4]
 [2 2 1]
 [3 1 4]]
E = 
 [[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-0.5        -0.5         1.        ]]

EA = 
 [[ 6.     5.     4.   ]
 [ 0.     0.333 -0.333]
 [-1.    -2.5    1.5  ]]


In [59]:
print(A)

[[2 7 2]
 [1 4 8]
 [3 6 3]]
